# Generated by Django 3.1.5 on 2021-01-08 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210108_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='interestedUsers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
