# Generated by Django 3.0.8 on 2021-01-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
