# Generated by Django 3.0.8 on 2021-02-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210214_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=5000),
        ),
    ]
