# Generated by Django 3.0.8 on 2021-02-19 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210217_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='interestedUsers',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
